feat : github-webhook, slack-webhook 연동
hegunhee/SpringPlayground pull request #9
Opened 2024-07-03 00:01 UTC by hegunhee

이 PR은 Github-webhook과 slackwebhook의 연동을 작업한 PR이며
webhook 테스트와 같이 진행될 예정이라 코멘트가 많이 달릴 예정입니다.

2024-07-03 00:03 UTC, hegunhee commented
코멘트테스트 1

2024-07-03 00:05 UTC, hegunhee commented
코멘트달기 2

2024-07-04 03:03 UTC, hegunhee commented
안녕하세요 저스틴, 현재 push, pr 이벤트 관련해서 github-webhook을 slack-webhook으로 전달하는 코드를 작성했습니다.

2024-07-08 00:16 UTC, liquidjoo requested changes
코멘트 남겼으니 확인해보면 좋을듯

2024-07-08 00:16 UTC, liquidjoo commented on src/main/java/com/example/SpringPlayground/githubWebhook/controller/GitHubWebhookController.java
> +        }
객체 책임, 역할등을 생각하면 너무 많은 분기가 있는 것 같은데
어떻게 풀어보면 좋을까?

2024-07-08 00:16 UTC, liquidjoo commented on src/main/java/com/example/SpringPlayground/githubWebhook/controller/GitHubWebhookController.java
> +        }
위의 코멘트 와 동일
코드 라인 같은거 한번 검토하면 좋을듯 특히 띄어쓰기

2024-07-08 00:16 UTC, liquidjoo commented on src/main/java/com/example/SpringPlayground/githubWebhook/controller/GitHubWebhookController.java
> +        }
더욱 간단하게 표현이 가능하지 않을까?

2024-07-08 00:16 UTC, liquidjoo commented on src/main/java/com/example/SpringPlayground/githubWebhook/model/github/GithubUser.java
> +@Data
Setter 에 대해서 열어 놓으면 객체지향적으로 어떤 어려움이 있을까?

2024-07-08 00:16 UTC, liquidjoo commented on src/main/java/com/example/SpringPlayground/githubWebhook/model/slack/blocks/Divider.java
> +public class Divider implements Block{
코드 라인

2024-07-08 00:16 UTC, liquidjoo commented on src/main/java/com/example/SpringPlayground/githubWebhook/model/slack/blocks/Block.java
> +public interface Block {
블럭의 역할이 뭔지 잘 모르겠네

2024-07-08 00:16 UTC, liquidjoo commented on src/test/java/com/example/SpringPlayground/githubWebhook/service/GithubDataToSlackTest.java
> +    private final SlackService slackService;
Mock으로 테스트해보는게 어때?
테스트할 때마다 스프링을 띄우면 너무 오래걸릴 것 같은데

2024-07-08 00:16 UTC, liquidjoo commented on src/test/java/com/example/SpringPlayground/githubWebhook/service/SlackServiceTest.java
> +    }
예외에 대한 테스트 코드를 작성해보면 좋을듯

2024-07-08 11:24 UTC, hegunhee commented on src/test/java/com/example/SpringPlayground/githubWebhook/service/GithubDataToSlackTest.java
> +    private final SlackService slackService;
해당 테스트 클래스에서 SlackService 클래스가 내부의 @Value 어노테이션이 spring의존성이 있어서
SlackServiceMock 클래스를 만들어서 @InjectMock으로 주입시켜 Mock 테스트했습니다.

2024-07-08 11:35 UTC, hegunhee commented on src/main/java/com/example/SpringPlayground/githubWebhook/controller/GitHubWebhookController.java
> +        }
앗.... 부끄럽네요

2024-07-08 13:30 UTC, hegunhee commented on src/main/java/com/example/SpringPlayground/githubWebhook/model/github/GithubUser.java
> +@Data
가장크게 캡슐화가 깨지게 됩니다.
그로인해서 특정 객체에게 기대하는 값을 얻기 어려워질 수 있습니다.

특정 객체의 프로퍼티값에대한 검증이 어려워지고 해당 검증을 다른 객체가 해야될수도 있습니다.
해당 예시를 들면 Image 객체의 type 프로퍼티의 경우 setter로 열어놓았을때
슬랙 메시지로 전달이 제대로 되지 않을 수 있습니다.

처음 생각했던게
@Getter, @ToString, @EqualsAndHashCode, @RequiredArgsConstructor, @NoArgsConstructor 만 설정하려했지만
코드 줄을 너무 많이 사용하는것같아서 @Data로 사용했습니다.

2024-07-08 15:04 UTC, hegunhee commented on src/test/java/com/example/SpringPlayground/githubWebhook/service/SlackServiceTest.java
> +    }
GithubMessage 파싱중 JsonProcessingException과
slack.send과정중 url을 잘못넣어 발생하는 IOException
Resource 위치 다르게 설정해서 IOException 예외 발생 테스트코드 작성했습니다.

2024-07-08 15:06 UTC, hegunhee commented on src/main/java/com/example/SpringPlayground/githubWebhook/model/slack/blocks/Block.java
> +public interface Block {
slack webhook에서 데이터를 받는 형태가 block이라는 이름으로 분리되어있어서
Block으로 처음에 지었습니다.

하지만 슬랙 페이로드의 요소라는 점이 중요한것같아 SlackPayloadComponent라고 변경하였습니다.

2024-07-17 23:45 UTC, liquidjoo requested changes
객체적으로 조금 더 생각해보면 좋을듯

2024-07-17 23:45 UTC, liquidjoo commented on src/main/java/com/example/SpringPlayground/githubWebhook/model/github/Commit.java
> +@ToString
ToString 을 사용하는 이유는?

2024-07-17 23:45 UTC, liquidjoo commented on src/main/java/com/example/SpringPlayground/githubWebhook/model/github/Commit.java
> +@NoArgsConstructor
해당 프로퍼티가 의미하는 것이 어떤 것인지 알고 사용하는 것인지?

2024-07-17 23:45 UTC, liquidjoo commented on src/main/java/com/example/SpringPlayground/githubWebhook/model/github/GithubUser.java
> +        Text userText = new Text("보낸 사람: " +userName, url);
해당 초기화는 매개변수로 하는 것이 맞을 지 생성자에서 하는 것이 맞을지?
생성자의 역할은 무엇인지

2024-07-17 23:45 UTC, liquidjoo commented on src/main/java/com/example/SpringPlayground/githubWebhook/model/github/pullrequest/PRMessage.java
> +        slackPayload.addComponent(userImage);
Divider 를 계속 초기화 해주는 이유는?

2024-07-17 23:45 UTC, liquidjoo commented on src/main/java/com/example/SpringPlayground/githubWebhook/model/github/push/PushMessage.java
> +    private List<Commit> commits;
일급 컬렉션을 활용해보면 어떤 결과물이 나올 수 있을까?
어떤 장점이 존재할까?

2024-07-17 23:45 UTC, liquidjoo commented on src/main/java/com/example/SpringPlayground/githubWebhook/model/github/push/PushMessage.java
> +    }
단일 책임 원칙을 고려해보면 어떻게 할 수 있을까?

2024-07-20 11:43 UTC, hegunhee commented
@liquidjoo 안녕하세요 저스틴 코멘트 주신내용들 보완해서 수정했습니다!

2024-07-21 06:33 UTC, hegunhee commented
안녕하세요 저스틴!
SlackPayload의 값들을 생성자에서 받아 객체를 만들어 보다 안전한 객체를 만들고
기존에 SlackPayload에서 components를 추가할 수 있던것을 삭제해 불변 객체로 만들었습니다

Text 객체의 경우 생성자가 두개라 사용자가 혼동이 올 수 있기때문에
정적 팩토리 메서드를 작성해 메서드 명으로 구분했습니다.

toString의 경우 현재 json으로 변경시킨 값을 디버깅중이므로 toString 롬북 어노테이션을 삭제했습니다.

2024-07-22 01:43 UTC, liquidjoo approved these changes
고생했어!

2024-07-22 08:52 UTC, hegunhee commented
감사합니다!

2024-07-22 08:52 UTC, merged